# Урок 3. Линейные преобразования

In [3]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Собственные значения:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-2\cdot(-6)=0,$$

$$\lambda^{2}-5\lambda +6=0,$$

$$\lambda=2, \lambda=3 $$

Собственные векторы:

$$\begin{cases}
-x_{1}-6x_{2}=2 x_{1}, \\
2x_{1}+6x_{2}=2 x_{2}.
\end{cases}; \begin{cases}
-3x_{1}-6x_{2}=0, \\
2x_{1}+4x_{2}=0.
\end{cases}; \begin{cases}
x_{1}=-2x_{2}, \\
x_{1}=-2x_{2}.
\end{cases}$$

$$\begin{cases}
-x_{1}-6x_{2}=3 x_{1}, \\
2x_{1}+6x_{2}=3 x_{2}.
\end{cases}; \begin{cases}
-4x_{1}-6x_{2}=0, \\
2x_{1}+3x_{2}=0.
\end{cases}; \begin{cases}
x_{1}=-1.5x_{2}, \\
x_{1}=-1.5x_{2}.
\end{cases}$$

Cобственные векторы x(-2, 1); x(-3,2)

**Решение через python**

In [2]:
a = np.array([[-1, -6], [2, 6]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]
v1
[ 0.83 -0.55]
v1
[ 0.83 -0.55]

1.0


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Возьмем вектор $x=\begin{pmatrix}
a\\ 
b
\end{pmatrix}$ :
$\textbf{A}x=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\begin{pmatrix}
a\\ 
b
\end{pmatrix} = \begin{pmatrix}
-1\cdot a+0\cdot b\\ 
0\cdot a-1\cdot b
\end{pmatrix} = \begin{pmatrix}
-a\\ 
-b
\end{pmatrix} = (-1)\begin{pmatrix}
a\\ 
b
\end{pmatrix} = -x$

Таким образом, произвольно взятый вектор $x=\begin{pmatrix}
a\\ 
b
\end{pmatrix}$ является собственным вектором данного поворота, заданного матрицей 𝐴, соответствующий собственному значению $\lambda=-1$.

**Решение через python**

In [3]:
w2, v2 = np.linalg.eig(np.array([[-1,0], [0, -1]]))
print('Собственные числа оператора ', w2)

Собственные числа оператора  [-1. -1.]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\begin{cases}
1+1=\lambda, \\
-1+3 =\lambda.
\end{cases}; \lambda=2$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$

**Решение через python**

In [4]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}= \lambda \begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix} $$

$\begin{cases}
-3\lambda-9 =0 \\
3\lambda+9=0 \\
4\lambda -12 = 0
\end{cases}; 
\begin{cases}
\lambda = -3 \\
\lambda = -3 \\
\lambda = 3
\end{cases};$

Нет единственного решения для системы уравнений.
Следовательно, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора

In [14]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
a1 = np.array([[3, -3, -4]])
a_ = np.dot(a, a1)
a_


ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [9]:
w, v = np.linalg.eig(a_)

print(f'Матрица A:\n{a_}')
print(f'Собственные значения:\n{w}')

LinAlgError: Last 2 dimensions of the array must be square