# Урок 2. Матрицы и матричные операции

In [1]:
import numpy as np
import scipy.linalg

### Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

$AB, BA$ - определить нельзя, т.к. необходимо, чтобы число столбцов матрицы  A  было равно числу строк матрицы B

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

$AB = 2 \times 3$;
$BA$ - определить нельзя, т.к. необходимо, чтобы число столбцов матрицы  A  было равно числу строк матрицы  B

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

$AB = 8 \times 8$
$BA = 3 \times 3$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

$AB = 4 \times 4$
$BA = 4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A + B = \begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix} + \begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix} = \begin{pmatrix} 1 + 4 & -2 + (-1) \\ 3 + 0 & 0 + 5 \end{pmatrix} = \begin{pmatrix} 5 & -3 \\ 3 & 5 \end{pmatrix} $$


$$A \times B = \begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix} \times \begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix} = \begin{pmatrix} 1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\ 3 \cdot (4) + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5 \end{pmatrix} = \begin{pmatrix} 4 & -11 \\ 12 & -3 \end{pmatrix} $$

**Решение через python**

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Матрица A + B\n{a + b}')
print(f'Матрица AB\n{a.dot(b)}')

Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A = 3 \cdot \begin{pmatrix} 1 & 7\\ 3 & -6 \end{pmatrix}  = \begin{pmatrix} 3 & 21\\ 9 & -18 \end{pmatrix}  $$
$$2B = 2 \cdot \begin{pmatrix} 0 & 5\\ 2 & -1 \end{pmatrix}  = \begin{pmatrix} 0 & 10\\ 4 & -2 \end{pmatrix}  $$
$$4C = 4 \cdot \begin{pmatrix} 2 & -4\\ 1 & 1 \end{pmatrix}  = \begin{pmatrix} 8 & -16\\ 4 & 4 \end{pmatrix}  $$
$$ 3A−2B+4C = \begin{pmatrix} 3 & 21\\ 9 & -18 \end{pmatrix} - \begin{pmatrix} 0 & 10\\ 4 & -2 \end{pmatrix} + \begin{pmatrix} 8 & -16\\ 4 & 4 \end{pmatrix} = \begin{pmatrix} 11 & -5\\ 9 & -12 \end{pmatrix} $$

**Решение через python**

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(f'Линейная комбинация  3𝐴−2𝐵+4𝐶 \n{3*a - 2* b + 4*c}')

Линейная комбинация  3𝐴−2𝐵+4𝐶 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix} 4 & 5 & 2 \\ 1 & -2 & 3 \end{pmatrix}$$$$A \times A^{T}=\begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix} \times \begin{pmatrix} 4 & 5 & 2 \\ 1 & -2 & 3 \end{pmatrix} = \begin{pmatrix} 4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\ 5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3 \\ 2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3 \end{pmatrix} = \begin{pmatrix} 17 & 18 & 11 \\ 18 & 29 & 4 \\ 11 & 4 & 13 \end{pmatrix}$$$$A^{T} \times A = \begin{pmatrix} 4 & 5 & 2 \\ 1 & -2 & 3 \end{pmatrix} \times \begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix} = \begin{pmatrix} 4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\ 1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3 \end{pmatrix} = \begin{pmatrix} 45 & 0 \\ 0 & 14 \end{pmatrix}$$

**Решение через python**

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')
print(f'A^TA\n{np.dot(a, a.T)}')
print(f'A^TA\n{np.dot(a.T, a)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
A^TA
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A^TA
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def dot_matrix(a, b):
    if len(a[0]) == len(b) and len(a) == len(b[0]):
        c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
        for m in range(len(a)):
            for n in range(len(a[0])):
                for k in range(len(b[0])):
                    c[m][k] = a[m][n] * b[n][k] + c[m][k]
    return c

In [6]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Работа Функции \n{dot_matrix(a, b)}')
print(f'Проверка функции \n{a.dot(b)}')

Работа Функции 
[[4, -11], [12, -3]]
Проверка функции 
[[  4 -11]
 [ 12  -3]]


### Часть 2


__1.__ Вычислить определитель:
   a)
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $\begin{pmatrix} sin(x) & -cos(x)\\ cos(x) & sin(x) \end{pmatrix} = sin^2(x) + cos^2(x) = 1$

б)
Матрица треугольного вида, определитель которой равен произведению диагональных элементов:    
$$\begin{pmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{pmatrix} = 4 \cdot 5 \cdot 9 = 180$$

   в)
$$\begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9 \end{pmatrix} = 1 \cdot \begin{pmatrix} 5 & 6\\ 8 & 9 \end{pmatrix} - 2 \cdot \begin{pmatrix} 4 & 6\\ 7 & 9 \end{pmatrix} + 3 \cdot \begin{pmatrix} 4 & 5\\ 7 & 8 \end{pmatrix} = 1 \cdot (5 \cdot 9 - 6 \cdot 8) - 2 \cdot (4 \cdot 9 - 6 \cdot 7) + 3 \cdot (4 \cdot 8 - 5 \cdot 7) = 0$$

**Решение через python**

In [7]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'б) Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

с = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'в) Матрица:\n{с}')
print(f'Определитель:\n{np.linalg.det(с):.0f}')

б) Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180
в) Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

а) $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;

б) $det(A^{T})= det(A) = 4$;

в) $det(2A) = 2 \cdot det(A) = 8$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется вырожденная, если определитель матрицы равен нулю

$$\begin{pmatrix} -2 & 7 & -3\\ 4 & -14 & 6\\ -3 & 7 & 13 \end{pmatrix} = -2 \cdot \begin{pmatrix} -14 & 6 \\ 7 & 13 \end{pmatrix} - 7 \cdot \begin{pmatrix} 4 & 6 \\ -3 & 13 \end{pmatrix} + (-3) \cdot \begin{pmatrix} 4 & -14 \\ 7 & 13 \end{pmatrix} = -2 \cdot (-14 \cdot 13 - 6 \cdot 7) - 7 (4 \cdot 13 - 6 \cdot (-3)) + (-3)\cdot (4 \cdot 7 - (-14)\cdot (-3)) = 0$$

**Решение через python**

In [8]:
b = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'б) Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

б) Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

a) $$\begin{pmatrix} 1 & 2 & 3\\ 1 & 1 & 1\\ 2 & 3 & 4 \end{pmatrix}$$ Третья строка является суммой первой и второй строк, а значит, ее можно отбросить: $$\begin{pmatrix} 1 & 2 & 3\\ 1 & 1 & 1 \end{pmatrix}$$
Поменяем 1 и 2 строки местами
$$\begin{pmatrix} 1 & 1 & 1 \\ 1 & 2 & 3 \end{pmatrix}$$
Вычтем из второй строки первую
$$\begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \end{pmatrix}$$
Ранг матрицы равен $2$


б) $$\begin{pmatrix} 0 & 0 & 2 & 1\\ 0 & 0 & 2 & 2\\ 0 & 0 & 4 & 3\\ 2 & 3 & 5 & 6 \end{pmatrix}$$
3 строка - это сумма 1 и 2 строк, значит ей убираем

$$ \begin{pmatrix} 0 & 0 & 2 & 1\\ 0 & 0 & 2 & 2\\ 2 & 3 & 5 & 6 \end{pmatrix}. $$
Ранг матрицы равен $3$

**Решение через python**

In [9]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'a) Ранг матрицы: {r}')

b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)

print(f'б) Ранг матрицы: {r}')

a) Ранг матрицы: 2
б) Ранг матрицы: 3
