### Урок 4. Системы линейных уравнений
### Часть 1

In [1]:
import numpy as np
from scipy import linalg

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы:

$$A = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} = \begin{pmatrix}
1 & 1 & -1 & -2 & | & 0\\ 
0 & -1 & 1 & 5 & | & -2\\ 
0 & 0 & -2 & 3 & | & 4
\end{pmatrix}$$

(Прибавим к второй стоке первую, умноженную на -2 (-2 -2 2 4 | 0), и к третьей первую, умноженную на -1 (-1 -1 1 2 | 0))

Оставшаяся матрица соответствует системе:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$
Бесконечное множество решений принято записывать в виде общего решения. В данном случае можно рассматривать в качестве свободного параметра  $x_{4}=c$ . Тогда, выражая остальные переменные через  c , получим:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
x_{3}=\frac{3c-4}{2},\\
 x_{4}=c
\end{cases}, \begin{cases}
x_{1}=-\frac{13c}{2}+\frac{3c}{2}+2c-2=-3c-2, \\
x_{2}=\frac{3c}{2}+5c=\frac{13c}{2}, \\
x_{3}=\frac{3c}{2}-2,\\
 x_{4}=c
\end{cases},$$
Таковым будет общее решение системы. Подставляя произвольные числа вместо  c , мы получим частное решение. Например, при  $c=0$ :

$x_{1}=-2, \\
x_{2}=0, \\
x_{3}=-2,\\
 x_{4}=0$
Параметр  c  может принимать бесконечное количество значений, при которых уравнения в системе будут обращаться в тождества.

Подставив общее решение в исходную систему, также получим тождества:
$$\begin{cases}
-2+0+2-0=0, \\
0-2+0=-2, \\
-2+0+6+0=4.
\end{cases}$$

**Проверка на python**

In [2]:
A = np.array([[1, 1, -1, -2, 0], [2, 1, -1, 1, -2], [1, 1, -3, 1, 4]])
A

array([[ 1,  1, -1, -2,  0],
       [ 2,  1, -1,  1, -2],
       [ 1,  1, -3,  1,  4]])

In [3]:
A[1, :] += (-2)*A[0, :]
A[2, :] += (-1)*A[0, :]
print(A)

[[ 1  1 -1 -2  0]
 [ 0 -1  1  5 -2]
 [ 0  0 -2  3  4]]


In [4]:
c =0 
x1 = -3*c-2
x2 = 6.5*c
x3 = 1.5*c -2
x4 = c
print(x1, '\t', x2, '\t', x3, '\t', x4,'\t')

-2 	 0.0 	 -2.0 	 0 	


In [5]:
print(x1+x2-x3-2*x4 ==0)
print(2*x1+x2-x3+x4 == -2)
print(x1+x2-3*x3+x4 == 4)

True
True
True


__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

a)$
\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\
2 & -5 & -3\\
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\
-17\\
0
\end{matrix}
\end{pmatrix}\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & -1 & 3\\
-3 & -5 & 2\\
-1 & 1 & 1
\end{matrix}\right|
\begin{matrix}
4\\
-17\\
0
\end{matrix}
\end{pmatrix}\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & -1 & 3\\
0 & -8 & -1\\
0 & 0 & 4
\end{matrix}\right|
\begin{matrix}
4\\
-17\\
4
\end{matrix}
\end{pmatrix}
$

Решение единственное, система совместна:
$\begin{cases}
x_{3} - x_{2} + 3x_{1} = 4, \\
-8x_{2} - x_{1} = -17, \\
x_{1} = 1;
\end{cases} = 
\begin{cases}
x_{1} = 1, \\
x_{2} = 2, \\
x_{3} = 3;
\end{cases}$

б) $
\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\
1 & -2 & 3\\
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\
-2\\
5
\end{matrix}
\end{pmatrix}\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\
1 & -2 & 3\\
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
1\\
-2\\
6
\end{matrix}
\end{pmatrix}
$
Система не совместна, не имеет решений

в) 
$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\
-2
\end{matrix}
\end{pmatrix}
$
$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
0 & -5 & -23
\end{matrix}\right|
\begin{matrix}
4\\
-14
\end{matrix}
\end{pmatrix}
$
$
x_3 = t\\
x_2 = (-14 + 23t)/-5\\
x_1 = 4 + 2(-14+23t)/5-5t
$
В данном случае можно рассматривать в качестве свободного параметра $x_{3}=c$. Тогда, выражая остальные переменные через c , получим:
$\begin{cases}
x_{1} + 2x_{2} + 5c = 4,\\
-5x_{2} - 23c = -14,\\
x_{3} = c
\end{cases} = 
\begin{cases}
x_{1} = 4 - 2\frac{14-23c}{5} - 5с , \\
x_{2} = \frac{14-23c}{5} ,\\
x_{3} = c
\end{cases} = 
\begin{cases}
x_{1} = \frac{21c}{5} - \frac{8}{5} ,\\
x_{2} = \frac{14-23c}{5},\\
x_{3} = c
\end{cases}$

Система совместная, неопределенная, имеет бесконечное число решений

**Проверка на python**

In [6]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a2= np.array([[4, -17, 0]])
a_ = np.append(a, a2.T, axis=1)

rank_a = np.linalg.matrix_rank(a)
rank_a_ =np.linalg.matrix_rank(a_)
print(f'a) {rank_a == rank_a_}')

b = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b2= np.array([[1, -2, 5]])
b_ = np.append(b, b2.T, axis=1)

rank_b = np.linalg.matrix_rank(b)
rank_b_ =np.linalg.matrix_rank(b_)
print(f'б) {rank_b == rank_b_}')

с = np.array([[1, 2, 5], [3, 1, -8]])
с2= np.array([[4, -2]])
с_ = np.append(с, с2.T, axis=1)

rank_c = np.linalg.matrix_rank(с)
rank_c_ =np.linalg.matrix_rank(с_)
print(f'в) {rank_c == rank_c_}')

a) True
б) False
в) True


Если Ранги матрицы коэффициентов и расширенной матрицы  совпадают и равны количеству неизвестных n, значит, по теореме Кронекера-Капелли, система линейных уравнений совместна и определена, то есть имеет единственное решение.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

$A=\begin{pmatrix}
\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{matrix}
\end{pmatrix}$
$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
3\\ 
0.4\\
4/3\\
0.5
\end{matrix}
\end{pmatrix}$
$Rank(A) = Rank(\tilde{A}) = 4$ Система определена и имеет единственное решение

**Проверка на python**

In [7]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0 ,0 ,0, 2]])
a1 = np.array([3, 2, 4, 1]).reshape((-1,1))
a_ = np.concatenate([a, a1], axis =1)
a_

array([[ 1,  3, -2,  4,  3],
       [ 0,  5,  0,  1,  2],
       [ 0,  0,  3,  0,  4],
       [ 0,  0,  0,  2,  1]])

In [8]:
np.linalg.matrix_rank(a) == np.linalg.matrix_rank(a_)

True

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$|A| = \begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 2$
$\begin{vmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{vmatrix} =
a \begin{vmatrix}
4 & 5 \\
7 & 8
\end{vmatrix} - b \begin{vmatrix}
1 & 2 \\
7 & 8
\end{vmatrix} + c \begin{vmatrix}
1 & 2 \\
4 & 5
\end{vmatrix} = -3a + 6b -3c = $ 
$-a + 2b -c$

$-a + 2b - c = 0$

$c = 2b - a$

При любых соотношений $a$, $b$ и $c$, кроме $c = 2b - a$ $rank A<rank \tilde A$ система несовместна.

### Часть 2 

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

а) $detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4\\ 
\end{vmatrix}= -4+6 = 2\neq 0,$

$detA_{1}=\begin{vmatrix}
1 & -2 \\ 
7 & -4\\ 
\end{vmatrix}= -4+14 = 10\neq 0,$
$detA_{2}=\begin{vmatrix}
1 & 1 \\ 
3 & 7 \\ 
\end{vmatrix}= 7-3 = 4\neq 0,$

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$
$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2,$$

б) $detA=\begin{vmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\
2 & 4 & 1 \\
\end{vmatrix}= 2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}
-1\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+5
\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix} = 2 \cdot (1+12) + 1 \cdot (1+6) + 5 \cdot (4-2)= 26+7+ 10 = 43 \neq 0$

$detA_{1}=\begin{vmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3 \\
1 & 4 & 1 \\
\end{vmatrix} = 1 \cdot \begin{vmatrix}
-1 & 5\\ 
1 & -3
\end{vmatrix} - 4 \cdot \begin{vmatrix}
10 & 5\\ 
-2 & -3
\end{vmatrix} + 1 \cdot \begin{vmatrix}
10 & -1\\ 
-2 & 1 
\end{vmatrix} = (-1 \cdot (-3) - 5 \cdot 1) - 4 \cdot (10 \cdot (-3) - 5 \cdot (-2)) + (10 \cdot 1 - (-1) \cdot (-2)) = -2 + 80 + 8 = 86 \neq 0,$

$detA_{2}=\begin{vmatrix}
2 & 10 & 5 \\ 
1 & -2 & -3 \\
2 & 1 & 1 \\
\end{vmatrix}= 2 \cdot \begin{vmatrix}
-2 & -3\\ 
1 & 1
\end{vmatrix} - 1 \cdot \begin{vmatrix}
10 & 5\\ 
1 & 1
\end{vmatrix} + 2 \cdot \begin{vmatrix}
10 & 5\\ 
-2 & -3
\end{vmatrix} = 2 \cdot ((-2) \cdot 1 - (-3) \cdot 1) - (10 \cdot 1 - 5 \cdot 1) + 2 \cdot (10 \cdot (-3) - 5 \cdot (-2)) = 2 - 5 - 40 = -43 \neq 0,$

$detA_{3}=\begin{vmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2 \\
2 & 4 & 1 \\
\end{vmatrix} = 2 \cdot \begin{vmatrix}
1 & -2\\ 
4 & 1
\end{vmatrix} - 1 \cdot \begin{vmatrix}
-1 & 10\\ 
4 & 1
\end{vmatrix} + 2 \cdot \begin{vmatrix}
-1 & 10\\ 
1 & -2
\end{vmatrix} = 2 \cdot (1 \cdot 1 - (-2) \cdot 4) - (-1 \cdot 1 - 10 \cdot 4) + 2 \cdot (-1 \cdot (-2) - 10 \cdot 1) = 18 + 41 - 16 = 43\neq 0,$

$x_{1}=\frac{detA_{1}}{detA} = \frac{86}{43} = 2$,
$x_{2}=\frac{detA_{2}}{detA} = \frac{43}{43} = -1$,
$x_{3}=\frac{detA_{3}}{detA} = \frac{43}{43} = 1$

**Проверка на python**

In [9]:
a = np.array([[1, -2], [3, -4]])
print(f'а) Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

а) Матрица:
[[ 1 -2]
 [ 3 -4]]
Определитель:
2


In [10]:
a1 = np.array([[1, -2], [7, -4]])
a2 = np.array([[1, 1], [3, 7]])

print(f'а) Матрица a1:\n{a1}')
print(f'Определитель a1:\n{np.linalg.det(a1):.0f}')

print(f'а) Матрица a2:\n{a2}')
print(f'Определитель a1:\n{np.linalg.det(a2):.0f}')

x1=np.round(np.linalg.det(a1)/np.linalg.det(a))
x2=np.round(np.linalg.det(a2)/np.linalg.det(a))
print(f'x1 = {x1},  x2= {x2}')

а) Матрица a1:
[[ 1 -2]
 [ 7 -4]]
Определитель a1:
10
а) Матрица a2:
[[1 1]
 [3 7]]
Определитель a1:
4
x1 = 5.0,  x2= 2.0


In [11]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'б) Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

б) Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


In [12]:
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'б) Матрица a1:\n{a1}')
print(f'Определитель a1:\n{np.linalg.det(a1):.0f}')

print(f'б) Матрица a2:\n{a2}')
print(f'Определитель a1:\n{np.linalg.det(a2):.0f}')

print(f'б) Матрица a3:\n{a3}')
print(f'Определитель a1:\n{np.linalg.det(a3):.0f}')

x1=np.round(np.linalg.det(a1)/np.linalg.det(a))
x2=np.round(np.linalg.det(a2)/np.linalg.det(a))
x3=np.round(np.linalg.det(a3)/np.linalg.det(a))
print(f'x1 = {x1},  x2= {x2}, x3 = {x3}')

б) Матрица a1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель a1:
86
б) Матрица a2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель a1:
-43
б) Матрица a3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель a1:
43
x1 = 2.0,  x2= -1.0, x3 = 1.0


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
$U = \begin{pmatrix}
3 & 26 & 30 \\
2 & 9 & 12 \\ 
1 & 2 & 4 \\ 
\end{pmatrix}$
$L = \begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}$
$U = \begin{pmatrix}
3 & 26 & 30 \\
0 & - \frac{25}{3} & -8 \\ 
0 & -\frac{20}{3} & -6 \\ 
\end{pmatrix}$
$U = \begin{pmatrix}
3 & 26 & 30 \\
0 & -8 \frac{1}{3} & -8 \\ 
0 & 0 & \frac{2}{5} \\ 
\end{pmatrix}$
$L = \begin{pmatrix} 
1 & 0 & 0 \\
\frac{2}{3} & 1 & 0 \\
\frac{1}{3} & \frac{4}{5} & 1
\end{pmatrix}$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
1 & 1 & 2 & 4
\end{pmatrix}$
$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\
0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} 
\end{pmatrix}$
$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\
0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} 
\end{pmatrix}$
$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\
0 & 0 & 2 \frac{5}{8} & 1 \frac{3}{8} 
\end{pmatrix}$
$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\
0 & 0 & 0 & - \frac{4}{41}
\end{pmatrix}$
$L = \begin{pmatrix} 
1 & 0 & 0 & 0 \\
\frac{1}{2} & 1 & 0 & 0 \\
\frac{3}{4} & -\frac{1}{4} & 1 & 0 \\
\frac{1}{4} & \frac{3}{4} & - \frac{7}{41} & 1
\end{pmatrix}$

**Проверка на python**

In [13]:
c = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
c

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [14]:
P, L, U = linalg.lu(c)
print(f'U =\n {U}')
print(f'L =\n {L}')

U =
 [[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]
L =
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


In [15]:
d = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
d

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [16]:
P, L, U = linalg.lu(d)

print(f'U =\n {U}')
print(f'L =\n {L}')

U =
 [[  4.          22.          53.          33.        ]
 [  0.          -6.         -18.5         -7.5       ]
 [  0.           0.         -15.375       -8.625     ]
 [  0.           0.           0.          -0.09756098]]
L =
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


$\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}\right|
\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix} \rightarrow 
\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
22 & 14 & 10\\ 
18 & 16 & 8
\end{matrix}\right|
\begin{matrix}
1\\ 
-12\\
-10
\end{matrix}
\end{pmatrix}$


U: $\begin{pmatrix}
2 & 1 & 3 \\ 
22 & 14 & 10 \\ 
18 & 16 & 8
\end{pmatrix} \rightarrow
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 7 & -19
\end{pmatrix} \rightarrow
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 0 & \frac{104}{3}
\end{pmatrix}=U$
L: $\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & l_{32} & 1
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & \frac{7}{3} & 1
\end{pmatrix}=L$

Решим систему $Ly=b$:
$\begin{cases}
y_1=1 \\
11y_{1}+y_2=-12 \\
9y_{1}+\frac{7}{3}y_{2}+y_{3}=-10
\end{cases} \Leftrightarrow
\begin{cases}
y_1=1 \\
y_2=-23 \\
y_{3}=\frac{104}{3}
\end{cases}$

Решим систему $Ux=y$:
$\begin{cases}
2x_1+x_2+3x_3=1 \\
3x_2-23x_3=-23 \\
\frac{104}{3}x_3=\frac{104}{3}
\end{cases} \Leftrightarrow
\begin{cases}
x_1=-1 \\
x_2=0 \\
x_3=1
\end{cases}$

**Проверка на python**

In [17]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
P, L, U = linalg.lu(a)
lu, piv = linalg.lu_factor(a)
x = np.round(linalg.lu_solve((lu, piv), b))
print(f' x_1 = {x[0]}\n x_2 = {x[1]}\n x_3 = {x[2]}')

 x_1 = -1.0
 x_2 = 0.0
 x_3 = 1.0


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$\begin{pmatrix}
81 & -45 & 45 \\
-45 & 50 & -15 \\
45 & -15 & 38
\end{pmatrix}$
$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$
$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$
$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$
$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - (-5)^2} = 5$
$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 - (-5) \cdot 5) = 2$
$l_{33} = \sqrt{a_{33}-l_{32}^{2}-l_{31}^{2}} = \sqrt{38 - 2^2 - 5^2} = 3$
$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}.$
$Ly=b:$
$\begin{cases}
    9 y_1 = 531 \\
    -5 y_1 + 5 y_2 = -460 \\
    5 y_1 + 2 y_2 + 3 y_3 = 193
\end{cases}$
$y_1 = 59$
$y_2 = -33$
$y_3 = -12$
$L^{T}x=y:$
$\begin{cases}
    9 x_1 - 5 x_2 + 5 x_3 = 59 \\
    5 x_2 + 2 x_3 = -33 \\
    3 x_3 = -12
\end{cases}$

$x_1 = 6$,
$x_2 = -5$,
$x_3 = -4$

**Проверка на python**

In [18]:
a = np.array([[81, -45, 45], [-45, 50, -15],[45, -15, 38]])
b = np.array([531, -460, 193])
np.linalg.solve(a, b)

array([ 6., -5., -4.])

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.